Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -19,14 +19,15 @@ trigger_internal_ci:
     DOWNSTREAM_PROJECT_ID: $DOWNSTREAM_PROJECT_ID
     DOWNSTREAM_PROJECT_NAME: $DOWNSTREAM_PROJECT_NAME
   script:
-    - |
-      set -e
-      echo $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
-      export TRIGGER_BRANCH=$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
-      #Creating a new branch
-      curl --request POST --header "PRIVATE-TOKEN: $SVC_HLS_RENDER_API" "https://main.gitlab.in.here.com/api/v4/projects/12500/repository/branches?branch=$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME&ref=master" || echo "failed to create branch"
+    - echo $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
+    - export TRIGGER_BRANCH=$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
+    - echo $DOWNSTREAM_PROJECT_ID
+    
+    - curl --request POST --header \
+        "PRIVATE-TOKEN: $SVC_HLS_RENDER_API" \
+        "${CI_SERVER_URL}/api/v4/projects/$DOWNSTREAM_PROJECT_ID/repository/branches?branch=$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME&ref=master" || echo "error creating branch $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME"
 
-      scripts/generate-config.sh
+    - scripts/generate-config.sh
   artifacts:
      paths:
       - generated-config.yml
